baseURL = 'https://zanyan.xyz/' # 记得改成你真实的 Netlify 网址
languageCode = 'zh-cn'
title = '麦花如雪'
theme = 'PaperMod'

[outputs]
    home = ["HTML", "RSS", "JSON"]

# 必须添加这个，否则 PaperMod 可能会报错
[params]
    defaultTheme = "light" # 固定浅色主题（深色模式在后续优化）
    ShowReadingTime = true # 显示阅读时间
    ShowShareButtons = false # 禁用分享按钮
    ShowToc = true # 启用文章目录
    math = true # 启用数学公式支持（KaTeX）
    hideCreditText = true # 隐藏页脚版权链接

    [params.assets]
        favicon = "https://i.imgur.com/3mQeOXJ.png" # 以后可以设置网页图标

    # 首页显示的个人简介配置
    [params.profileMode]
        enabled = true
        title = "你好，我是..."
        subtitle = "zanyyan123"
        imageUrl = "https://avatars.githubusercontent.com/u/87598107?s=400&u=70cc5b899b52c270f072a77e216acb4e3eb464fd&v=4" # 头像链接
        imageTitle = "我的头像"
        imageWidth = 120
        imageHeight = 120

    # 社交链接配置（GitHub, Email 等）
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/user14412"

[[menu.main]]
    name = "文章"
    url = "/posts"
    weight = 1

[[menu.main]]
    name = "搜索"
    url = "/search"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # 允许HTML渲染
  [markup.highlight]
    noClasses = false  # 确保语法高亮正常工作
